### ISSUE TITLE
[Meta] Doc formats

### ISSUE THREAD

**Issue by dalehamel** [bpftools/bpf.sh#2]
To serve http://blog.srvthe.net/usdt-report-doc/, I use travis to build the site and upload the rendered content to github pages by overwriting a special branch after committing.

I write the docs in markdown, and use pandoc with a github-resembling theme to render HTML. The build process also outputs PDF (via LaTeX), and epub formats. These may require some special optimization, especially for handling codeblocks and images, to ensure that the render nicely on all platforms (if you care). While it might seem like overkill, I kind of like it because:

* The HTML is most easily accessible and easy to make look good
* The PDF format looks quite professional / academic as it uses LaTeX, and is guaranteed to predictably look the same
* The ePub format, while trickier, makes it easy to make little "novelas" on particular topics, and could eventually give way to each publication being a chapter or section of a bigger ebook. The ePub format works an consumer eReaders and is the most enjoyable to read if rendered properly, as eInk is usually easier on the eyes, and can read a broader audience.

I think this framework could be generally useable by other reports, as I also added the ability to very trivially pull in codeblocks to annotate / comment on. Just adding github submodules, and indicating the file path, start and end line to insert, and language for syntax highlighting. I like just outputting all formats, but we could tune this pretty easily. Right now I am only building html for the report on bpf.sh

However, as long as the makefile just adds another target for each new doc, it shouldn't matter what the page build process is for each report.

If we want the site to have a similar look, then this pandoc solution can be used as a base / default, and any other doc formats can work about as well. The pandoc approach I used accepts markdown files, as well as some pandoc extensions, such as to generate the bibliography for easy attribution.

The extensions / conventions that I mention above should probably be agreed upon by each of us, and documented somewhere (CONTRIBUTING.md?)

**Comment by dalehamel** [comment]
@leodido @fntlnz WDYT?

**Comment by leodido** [comment]
I really love pandoc 💟 .
Glad I am not the only one loving it here! 

I vaguely remember doing crazy things with it, R language, markdown pieces, and TeX when I was younger and with a lot of spare time 😃 (for example [here](https://github.com/leodido/markarticle)).

I think it's clear now that I vote for pandoc for a whole set of reasons ..

Anyway I'm not sure that the CONTRIBUTING.md file would be the better place to document this process. Probably it's just documentation about this repository setup.

**Comment by fntlnz** [comment]
I like all that is written here @dalehamel

**Comment by dalehamel** [comment]
This should all be done on master i think

**Comment by dalehamel** [comment]
closed by #6
