### ISSUE TITLE
Github Pages builds failing

### ISSUE THREAD

**Issue by dalehamel** [bpftools/bpf.sh#3]
The way that I built my usdt-report-doc used submodules to easily pull in code i want to annotate / discuss in the report. 

One of the repos (bcc) has a symlink that appears broken, and the github pages builder that just looks at the /docs folder to serve it is panicking and bailing out when it doesn't need to.

For my builds of usdt-report-doc, I used travis to build the pages which is why i never encountered this issue.

I'd recommend we follow the same steps, and use travis to call the makefile and then output it. https://docs.travis-ci.com/user/deployment/pages/

A major benefit of this approach is that the rendered output doesn't need to be stored in the repo, travis will push it to a special branch that serves github pages only, so the source and renedered output can be separated, keeping the clone size much smaller.

I recommend we go with the travis approach, as it is more flexible. WDYT @fntlnz @leodido ?

**Comment by leodido** [comment]
I think it's a clean and straightforward approach.

I would personally only evaluate whether also other CI services offer such feature.

**Comment by dalehamel** [comment]
It looks like circle supports it as well, I get there will always be a free tier CI for open source that supports this workflow

**Comment by dalehamel** [comment]
I've fixed this, sorry for the delay! It's up and working now
